# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPRTracker
                                 A QGIS plugin
 GNSS tracking
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-26
        copyright            : (C) 2020 by OsGeoLabBP
        email                : siki.zoltan@epito.bme.hu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPRTracker class from file GPRTracker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gpr_tracker import GPRTracker
    return GPRTracker(iface)
