# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPRTrackerDockWidget
                                 A QGIS plugin
 GNSS tracking
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-26
        git sha              : $Format:%H$
        copyright            : (C) 2020 by OsGeoLabBP
        email                : siki.zoltan@epito.bme.hu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsMapLayerProxyModel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gpr_tracker_dockwidget_base.ui'))


class GPRTrackerDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, plugin, parent=None):
        """Constructor."""
        super(GPRTrackerDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.plugin = plugin
        self.setupUi(self)
        self.trackOn.stateChanged.connect(self.state)
        self.trackLayer.setFilters(QgsMapLayerProxyModel.PointLayer)
        self.trackLayer.layerChanged.connect(self.trackLayer.setLayer)

    def state(self):
        if self.trackOn.isChecked():
            # disable all widget during tracking except checkbox
            self.trackLayer.setEnabled(False)
            self.trackColor.setEnabled(False)
            self.plugin.startTracking(True)
        else:
            # enable all widget if tracking off
            self.trackLayer.setEnabled(True)
            self.trackColor.setEnabled(True)
            self.plugin.startTracking(False)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
